variables:
  GIT_STRATEGY: clone

build-job:
  stage: build
  tags:
    - ugrad
  script:
    - mvn clean compile
  only:
    - develop
test-job:
  stage: test
  tags:
    - ugrad
  script:
    - mvn verify
  only:
    - develop
deploy-tested:
  stage: deploy
  tags:
    - docker_sports_runner
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_TEST --api-key=$HEROKU_API_KEY
  only:
    - develop
deploy-prod:
  stage: deploy
  tags:
    - docker_sports_runner
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - release_08_04_2021


